### ISSUE TITLE
ERROR: No matching distribution found for jaxlib==0.3.14

### ISSUE THREAD

**Issue by syheliel** [ise-uiuc/NablaFuzz#1]
Hi, first congrats on being accepted by ICSE'23. I'm trying to run NablaFuzz, but I encountered some environmental problems. I'd appreciate it if you would take the time to take a look.  @YangChenyuan @dengyinlin @YaoJiayi 
# error msg
```
ERROR: Could not find a version that satisfies the requirement jaxlib==0.3.14 (from versions: 0.4.3, 0.4.4, 0.4.6, 0.4.7, 0.4.9, 0.4.10, 0.4.11, 0.4.12, 0.4.13, 0.4.14, 0.4.16, 0.4.17, 0.4.18, 0.4.19, 0.4.20, 0.4.21, 0.4.22, 0.4.23, 0.4.24, 0.4.25)
ERROR: No matching distribution found for jaxlib==0.3.14
```
# reproduce
```
conda create -n nablafuzz python==3.9 mongodb mongo-tools
pip install -r ./requirements.txt
```

**Comment by YangChenyuan** [comment]
Hi, thanks for your interest in NablaFuzz!

For the installation error, it seems that we cannot use pip to directly install older version of `jaxlib`. Instead, you could use the following commands to install:

```
# Install jaxlib on CPU via the wheel archive
pip install jax[cpu]==0.3.14 -f https://storage.googleapis.com/jax-releases/jax_releases.html
# Install the jaxlib 0.3.25 CPU wheel directly
pip install jaxlib==0.3.14 -f https://storage.googleapis.com/jax-releases/jax_releases.html
```

For more information, please see this pull request: https://github.com/ise-uiuc/NablaFuzz/pull/2

**Comment by syheliel** [comment]
@YangChenyuan Thanks! this solves the problem.
